Repository CS2103-AY1819S1-T13-4/main, pull requests merged in 2018-10, with the labels that each got.

#33 Update Portfolio
  docs/images/bugeyedbug.png
  docs/team/bugeyedbug.adoc
Labels: priority.High, status.Review

#30 Update UI.png
  docs/images/Ui.png
Labels: priority.High, status.Review

#31 Update User Guide
  docs/UserGuide.adoc
Labels: status.Review

#23 Calculate current cap
  src/main/java/seedu/address/logic/commands/CapCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Transcript.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/TranscriptTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/systemtests/CapCommandSystemTest.java
Labels: status.Review

#24 Added add module command
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
Labels: priority.High, status.Review

#27 Transcript JSON storage
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTranscript.java
  src/main/java/seedu/address/model/Transcript.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/util/ModuleBuilder.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonTranscriptDeserializer.java
  src/main/java/seedu/address/storage/JsonTranscriptStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TranscriptStorage.java
  src/test/data/JsonTranscriptStorageTest/DuplicateModuleTranscript.json
  src/test/data/JsonTranscriptStorageTest/EmptyTranscript.json
  src/test/data/JsonTranscriptStorageTest/ExtraValuesTranscript.json
  src/test/data/JsonTranscriptStorageTest/InvalidAndValidTranscript.json
  src/test/data/JsonTranscriptStorageTest/InvalidTranscript.json
  src/test/data/JsonTranscriptStorageTest/NotJsonFormatTranscript.json
  src/test/data/JsonTranscriptStorageTest/TypicalTranscript.json
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
  src/test/java/seedu/address/storage/JsonTranscriptStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/SystemTestSetupHelper.java
Labels: priority.High, status.Review

#39 Fix wrong link alexkmj.jpg to alexkmj.png
  docs/AboutUs.adoc
Labels: priority.High, severity.Low, status.Review, type.Bug

#48 Update docs
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: severity.Low, status.Review

#46 Fix reposense
  .gitignore
  _reposense/config.json
Labels: priority.High, severity.Medium, status.Review

#35 Add Author Annotation
  src/main/java/seedu/address/logic/commands/CapCommand.java
  src/main/java/seedu/address/logic/commands/GoalCommand.java
  src/main/java/seedu/address/logic/parser/GoalCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Transcript.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/test/java/seedu/address/logic/parser/GoalCommandParserTest.java
  src/test/java/seedu/address/model/TranscriptTest.java
  src/test/java/systemtests/CapCommandSystemTest.java
  src/test/java/systemtests/GoalCommandSystemTest.java
Labels: status.Review

#52 Gui layout
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.High

#54 Added Parser for Module and Transcript
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TranscriptParser.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/util/ModuleBuilder.java
  src/test/java/seedu/address/logic/parser/AddModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TranscriptParserTest.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, severity.High, status.Review

#64 Logic router for TranscriptParser
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/TranscriptParser.java
Labels: priority.High, severity.High, status.Ongoing

#37 Implement Calculate target module grade in Transcript Class
  src/main/java/seedu/address/model/Transcript.java
  src/main/java/seedu/address/model/module/Grade.java
  src/main/java/seedu/address/model/module/Module.java
  src/test/java/seedu/address/model/TranscriptTest.java
  src/test/java/seedu/address/model/module/GradeTest.java
Labels: priority.High, severity.High

#66 Calculate Target Grade triggers
  src/main/java/seedu/address/model/Transcript.java
  src/main/java/seedu/address/model/capgoal/CapGoal.java
  src/main/java/seedu/address/model/module/Grade.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/test/java/seedu/address/model/TranscriptTest.java
  src/test/java/seedu/address/model/module/GradeTest.java
Labels: priority.High, status.Review

#72 Undo/Redo Command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/RedoModuleCommand.java
  src/main/java/seedu/address/logic/commands/UndoModuleCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RedoModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoModuleCommandTest.java
Labels: priority.Medium, status.Review

#97 System test setup
  src/test/java/seedu/address/TestApp.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ModelHelper.java
Labels: priority.High, status.Review

#95 Acknowledge SE-EDU3/4 in README.adoc
  README.adoc
Labels: priority.High, severity.Low, status.Review, type.Task

#93 Module code and grade value set to uppercase
  src/main/java/seedu/address/model/module/Code.java
  src/main/java/seedu/address/model/module/Grade.java
Labels: priority.Medium, status.Review, type.Bug

#79 refractor CapGoal change names and signatures
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Transcript.java
  src/main/java/seedu/address/model/capgoal/CapGoal.java
  src/test/java/seedu/address/model/TranscriptTest.java
Labels: priority.High, status.Review, type.Enhancement

#99 Update Use case to follow MSS and Extensions
  docs/DeveloperGuide.adoc
Labels: priority.High, status.Review, type.Enhancement, type.Task

#78 Added delete module command, Change logic for isSameModule
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/TranscriptParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Transcript.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteModuleCommandParserTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
Labels: priority.High, status.Review, type.Bug, type.Story

#88 Fix cap goal command doc
  docs/UserGuide.adoc
Labels: severity.High, status.Review, type.Bug

#89 Add sequence diagrams for Target Grade and CAP calculation
  docs/diagrams/TranscriptCapAndTargetSequenceDiagram.pptx
Labels: priority.High, status.Review, type.Task

#112 Update Model component of Developer Guide
  docs/DeveloperGuide.adoc
  docs/images/ModelClassDiagram_Transcript.png
Labels: priority.High, status.Review, type.Task

#113 Fix bug for ParserUtil.tokenizer and enforce use of constants in TestUtil.TypicalModules
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, status.Review, type.Bug

#102 Updated UI Features
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/ui/ModulePanelSelectionChangedEvent.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/ModuleCard2.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
  src/main/java/seedu/address/ui/ModuleListPanel2.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListCard2.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/ModuleListPanel2.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/ModuleCardHandle.java
  src/test/java/guitests/guihandles/ModuleListPanelHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/seedu/address/ui/ModuleCardTest.java
  src/test/java/seedu/address/ui/ModuleListPanelTest.java
  src/test/java/seedu/address/ui/PersonCardTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/CapCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/ErrorDialogGuiTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/GoalCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.High, severity.High, status.Ongoing, type.Task

#71 Adjust command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AdjustCommand.java
  src/main/java/seedu/address/logic/parser/AdjustCommandParser.java
  src/main/java/seedu/address/logic/parser/TranscriptParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Transcript.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/AdjustCommandTest.java
  src/test/java/seedu/address/logic/parser/AdjustCommandParserTest.java
  src/test/java/seedu/address/model/TranscriptTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, severity.High, type.Story

#126 Display correct modules for the two panels
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, severity.High, status.Review, type.Task

#76 Display Current CAP and CAP Goal
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/CapPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CapPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: status.Review

#119 Update Developer Guide - Design - Storage
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/StorageClassDiagram.png
Labels: priority.High, status.Review

#130 Update Userguide
  docs/UserGuide.adoc
Labels: priority.High, status.Review, type.Task

#133 Fix bugs in delete command
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/parser/DeleteModuleCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, status.Review, type.Bug

#129 target grades not updating
  src/main/java/seedu/address/model/Transcript.java
  src/main/java/seedu/address/model/capgoal/CapGoal.java
  src/main/java/seedu/address/model/module/Grade.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/storage/JsonTranscriptDeserializer.java
  src/main/java/seedu/address/ui/CapPanel.java
  src/test/data/JsonTranscriptStorageTest/ExtraValuesTranscript.json
  src/test/data/JsonTranscriptStorageTest/TypicalTranscript.json
  src/test/java/seedu/address/model/module/ModuleTest.java
Labels: priority.High, severity.High, status.Review, type.Bug

#132 Updated CAP Goal UI design
  src/main/java/seedu/address/ui/CapPanel.java
  src/main/resources/view/CapPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, severity.High, status.Review, type.Story

#135 Add Edit Command Feature
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TranscriptParser.java
  src/main/java/seedu/address/model/util/ModuleBuilder.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, status.Review, type.Story
