Repository CS2103-AY1819S1-T13-4/main, pull requests merged in 2018-11, with the labels that each got.

#139 Fix delete command logic
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
Labels: priority.High, severity.High, status.Review, type.Bug

#138 Fix bug for edit module command
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/test/java/seedu/address/logic/commands/EditModuleCommandTest.java
Labels: priority.High, severity.High, status.Review, type.Bug

#148 Fix parsing bugs, refactor code, added more unit test
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/Grade.java
  src/test/java/seedu/address/logic/commands/EditModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/EditModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, severity.High, status.Review, type.Bug

#185 Meaningful error message when goal is out of range
  src/main/java/seedu/address/logic/parser/GoalCommandParser.java
  src/test/java/seedu/address/logic/parser/GoalCommandParserTest.java
Labels: priority.Medium, severity.Low, status.Review, type.Bug

#187 Calls modulesUpdated on removeModule
  src/main/java/seedu/address/model/Transcript.java
Labels: priority.High, severity.High, status.Review, type.Bug

#188 Update Adjust Command in User Guide
  docs/UserGuide.adoc
Labels: priority.High, severity.High, status.Review, type.Bug

#189 Remove CapCommand
  src/main/java/seedu/address/logic/commands/CapCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TranscriptParser.java
  src/test/java/systemtests/CapCommandSystemTest.java
Labels: priority.High, severity.High, status.Review, type.Bug

#184 Write more test for TranscriptParser
  src/test/java/seedu/address/logic/parser/TranscriptParserTest.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
Labels: priority.Medium, severity.Low, status.Review, type.Task

#186 Prevent Adjust Command from updating Completed Module
  src/main/java/seedu/address/logic/commands/AdjustCommand.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/util/ModuleBuilder.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/AdjustCommandTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, severity.High, type.Bug

#193 Updated UserGuide.adoc to reflect the updated edit command
  docs/UserGuide.adoc
Labels: priority.High, severity.Medium, status.Review

#194 Documentation/target/calculation specs
  docs/DeveloperGuide.adoc
  docs/images/SDTranscriptCalculateCap.png
  docs/images/SDTranscriptModulesUpdate.png
  docs/images/SDTranscriptTargetCalculation.png
  src/main/java/seedu/address/logic/commands/AdjustCommand.java
  src/main/java/seedu/address/model/Transcript.java
  src/main/java/seedu/address/model/module/exceptions/ModuleCompletedException.java
  src/test/java/seedu/address/model/TranscriptTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
Labels: priority.High, severity.High, type.Story

#198 Update jeremiah-ang's PPP
  docs/team/jeremiah-ang.adoc
Labels: priority.High, severity.High, status.Review, type.Task

#200 Fix menu bar bug
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, severity.Medium, status.Review, type.Bug

#196 Delete now uses name value pair
  src/main/java/seedu/address/logic/commands/CommandUtil.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/DeleteModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/arguments/DeleteArgument.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/EditModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TranscriptParserTest.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
Labels: priority.High, severity.High, status.Review, type.Bug, type.Enhancement

#208 Add logs to CAP and Target Grade Calculation
  src/main/java/seedu/address/model/Transcript.java
  src/main/java/seedu/address/model/exceptions/CapGoalIsImpossibleException.java
  src/main/java/seedu/address/model/exceptions/NoTargetableModulesException.java
  src/main/java/seedu/address/model/module/Grade.java
  src/test/java/seedu/address/model/TranscriptTest.java
Labels: priority.High, severity.High, type.Enhancement

#206 Add more tests for CAP calculation and Documentation Update
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/jeremiah-ang.adoc
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/CapPanel.java
  src/test/java/seedu/address/model/TranscriptTest.java
Labels: priority.High, severity.High, type.Enhancement

#207 Remove legacy command & add more tests
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AdjustCommand.java
  src/main/java/seedu/address/logic/commands/GoalCommand.java
  src/main/java/seedu/address/logic/parser/AdjustCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TranscriptParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AdjustCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/TranscriptParserTest.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: priority.High, severity.High, type.Bug

#210 Update user guide documentation to reflect changes in edit command
  docs/UserGuide.adoc
Labels: priority.High, severity.Low, status.Review, type.Task

#215 Update user guide documentation to reflect changes in add command and other commands
  docs/UserGuide.adoc
Labels: priority.High, severity.Medium, status.Review, type.Story

#213 Add now uses name value pair
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/arguments/AddArgument.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddModuleCommandParserTest.java
  src/test/java/seedu/address/testutil/ModuleUtil.java
Labels: priority.High, severity.High, status.Review, type.Enhancement, type.Story

#211 Added getOnlyOneModule
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AdjustCommand.java
  src/main/java/seedu/address/logic/commands/CommandUtil.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Transcript.java
  src/main/java/seedu/address/model/VersionedTranscript.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/module/exceptions/MultipleModuleEntryFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/model/module/UniqueModuleListTest.java
Labels: priority.Medium, severity.Low, status.Review, type.Enhancement

#203 AddressBook systemtest update
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ModelHelper.java
Labels: priority.High, status.Review

#216 Developer guide update - Changed Ui.png and UiClassDiagram.png
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/AdjustCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/GoalCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/AdjustCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/AddModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AdjustCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, severity.High, status.Review

#218 Update alexkmj PPP
  docs/UserGuide.adoc
  docs/team/alexkmj.adoc
Labels: priority.High, status.Ongoing, type.Task

#220 Update Jeremiah PPP and Fix bugs
  docs/DeveloperGuide.adoc
  docs/images/SDTranscriptCalculateCap.png
  docs/images/activityDiagramTargetGradeCalculationActualCalculation.png
  docs/images/activityDiagramTargetGradeCalculationWhenChanged.png
  docs/team/jeremiah-ang.adoc
  src/main/java/seedu/address/model/Transcript.java
  src/test/java/seedu/address/model/TranscriptTest.java
Labels: priority.High, severity.High, type.Enhancement

#224 Update userguide
  docs/UserGuide.adoc
Labels: priority.High, status.Review

#229 Update Use Case documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.High, severity.High, type.Enhancement

#221 Jeremy PPP, small edits to User Guide, empty initial transcript data
  docs/DeveloperGuide.adoc
  docs/team/jeremyyew.adoc
  src/main/java/seedu/address/MainApp.java
Labels: priority.High, status.Review

#227 Updated FAQ in UserGuide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/josephambe.adoc
Labels: priority.High, severity.Medium, status.Review, type.Enhancement, type.Task

#230 Update Developer Guide - Logic
  docs/DeveloperGuide.adoc
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/images/DeleteModuleForLogic.png
  docs/images/LogicClassDiagram.png
Labels: priority.High, status.Review, type.Task

#232 Update Diagrams
  docs/DeveloperGuide.adoc
  docs/diagrams/activityDiagramTargetGradeCalculation.pptx
  docs/images/activityDiagramTargetGradeCalculationActualCalculation.png
  docs/images/activityDiagramTargetGradeCalculationWhenChanged.png
  docs/team/jeremiah-ang.adoc
Labels: priority.High, severity.High, status.Review, type.Enhancement

#228 Fix userguide and javadocs bug
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
Labels: priority.High, status.Review, type.Bug

#235 Update alex's PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/alexkmj.adoc
Labels: priority.High, severity.High, status.Review, type.Task

#231 Update to Diagrams in developer guide
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureDiagram.pptx
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/images/Architecture.png
  docs/images/LogicClassDiagram.png
  docs/images/SDforDeleteModule.png
  docs/images/SDforDeleteModuleEventHandling.png
  docs/images/SDforDeletePerson.png
  docs/images/SDforDeletePersonEventHandling.png
Labels: priority.High, severity.Low, status.Review

#236 added roles
  docs/AboutUs.adoc
Labels: priority.High, status.Review, type.Task

#237 Jeremy PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/jeremyyew.adoc
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: severity.High, type.Task
